name: "BMS Pace"
description: "Pace BMS Interface"
version: "3.0.1"
slug: "bms_pace"
url: "https://github.com/andrevza/bmspace"
init: false
host_network: false
privileged: []
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
uart: true
usb: true

options:
  mqtt_host: "10.0.0.132"
  mqtt_port: 1883
  mqtt_user: "mqtt-users"
  mqtt_password: "mqtt-users"
  mqtt_ha_discovery: true
  mqtt_ha_discovery_topic: "homeassistant"
  mqtt_base_topic: "bmspace"
  connection_type: "IP"
  bms_ip: "10.0.0.161"
  bms_port: 5000
  bms_serial: "/dev/ttyUSB0"
  scan_interval: 5
  debug_output: 0
schema:
  mqtt_host: "str"
  mqtt_port: "port"
  mqtt_client_id: "str?"
  mqtt_user: "str"
  mqtt_password: "password"
  mqtt_ha_discovery: "bool"
  mqtt_ha_discovery_topic: "str"
  mqtt_base_topic: "str"
  connection_type: "list(IP|Serial)"
  bms_ip: "str?"
  bms_port: "port?"
  bms_serial: "str?"
  scan_interval: "int"
  debug_output: "int"
  mqtt_discovery_cleanup_startup: "bool?"
  bms_connect_retries: "int?"
  bms_connect_retry_delay: "int?"
  force_pack_offset: "int?"
  packs_to_read: "int?"
  zero_pad_number_cells: "int?"
  zero_pad_number_packs: "int?"
